-- colors.lua
-- Auto-generated by matugen. DO NOT EDIT MANUALLY.
-- Re-run matugen with your wallpaper to regenerate.
-- Template: ~/.config/matugen/templates/hyprland-colors.lua

colors = {}

<* for name, value in colors *>
colors.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>
