-- colors.lua
-- Auto-generated by matugen. DO NOT EDIT MANUALLY.
-- Re-run matugen with your wallpaper to regenerate.
-- Template: ~/.config/matugen/templates/hyprland-colors.lua

colors = {}


colors.background = "rgba(141318ff)"

colors.error = "rgba(ffb4abff)"

colors.error_container = "rgba(93000aff)"

colors.inverse_on_surface = "rgba(312f36ff)"

colors.inverse_primary = "rgba(5f5791ff)"

colors.inverse_surface = "rgba(e5e1e9ff)"

colors.on_background = "rgba(e5e1e9ff)"

colors.on_error = "rgba(690005ff)"

colors.on_error_container = "rgba(ffdad6ff)"

colors.on_primary = "rgba(30285fff)"

colors.on_primary_container = "rgba(e5deffff)"

colors.on_primary_fixed = "rgba(1b1149ff)"

colors.on_primary_fixed_variant = "rgba(473f77ff)"

colors.on_secondary = "rgba(312e41ff)"

colors.on_secondary_container = "rgba(e5dff9ff)"

colors.on_secondary_fixed = "rgba(1c192bff)"

colors.on_secondary_fixed_variant = "rgba(484459ff)"

colors.on_surface = "rgba(e5e1e9ff)"

colors.on_surface_variant = "rgba(c9c5d0ff)"

colors.on_tertiary = "rgba(482536ff)"

colors.on_tertiary_container = "rgba(ffd8e6ff)"

colors.on_tertiary_fixed = "rgba(301120ff)"

colors.on_tertiary_fixed_variant = "rgba(623b4cff)"

colors.outline = "rgba(938f99ff)"

colors.outline_variant = "rgba(48454eff)"

colors.primary = "rgba(c9bfffff)"

colors.primary_container = "rgba(473f77ff)"

colors.primary_fixed = "rgba(e5deffff)"

colors.primary_fixed_dim = "rgba(c9bfffff)"

colors.scrim = "rgba(000000ff)"

colors.secondary = "rgba(c9c3dcff)"

colors.secondary_container = "rgba(484459ff)"

colors.secondary_fixed = "rgba(e5dff9ff)"

colors.secondary_fixed_dim = "rgba(c9c3dcff)"

colors.shadow = "rgba(000000ff)"

colors.source_color = "rgba(584c9dff)"

colors.surface = "rgba(141318ff)"

colors.surface_bright = "rgba(3a383eff)"

colors.surface_container = "rgba(201f25ff)"

colors.surface_container_high = "rgba(2b292fff)"

colors.surface_container_highest = "rgba(35343aff)"

colors.surface_container_low = "rgba(1c1b20ff)"

colors.surface_container_lowest = "rgba(0e0d13ff)"

colors.surface_dim = "rgba(141318ff)"

colors.surface_tint = "rgba(c9bfffff)"

colors.surface_variant = "rgba(48454eff)"

colors.tertiary = "rgba(edb8cdff)"

colors.tertiary_container = "rgba(623b4cff)"

colors.tertiary_fixed = "rgba(ffd8e6ff)"

colors.tertiary_fixed_dim = "rgba(edb8cdff)"

