-- monitors.lua
-- Monitor configuration
-- Generated by nwg-displays on 2025-08-13 at 21:48:09.
-- https://wiki.hypr.land/Configuring/Basics/Monitors/

hl.monitor({
    output   = "DP-3",
    mode     = "2560x1080@144",
    position = "2560x1080",
    scale    = 1,
})

hl.monitor({
    output    = "HDMI-A-1",
    mode      = "2560x1080@75.97",
    position  = "2560x0",
    scale     = 1,
    transform = 2,
})
