cursor #eedfe2
cursor_text_color #d5c2c7

foreground            #eedfe2
background            #191114
selection_foreground  #412933
selection_background  #e1bdc9
url_color             #ffb0ce

color0   #191114
color1   #ff7279
color2   #a0ff7f
color3   #ffe172
color4   #f298ba
color5   #76324c
color6   #ffb0ce
color7   #ffeff5
color8   #a5999e
color9   #ff9fa3
color10  #bcffa5
color11  #ffeca5
color12  #ffbbd5
color13  #ffc7dc
color14  #ffdbe8
color15  #fff8fb
