cursor #e5e1e9
cursor_text_color #c9c5d0

foreground            #e5e1e9
background            #141318
selection_foreground  #312e41
selection_background  #c9c3dc
url_color             #c9bfff

color0   #141318
color1   #ff7291
color2   #7fff98
color3   #ffd972
color4   #b4a9f2
color5   #483f76
color6   #c9bfff
color7   #f2efff
color8   #9b99a5
color9   #ff9fb4
color10  #a5ffb7
color11  #ffe7a5
color12  #d1c8ff
color13  #d9d2ff
color14  #e6e2ff
color15  #f9f8ff
