cursor #e9e2d4
cursor_text_color #cdc6b4

foreground            #e9e2d4
background            #16130b
selection_foreground  #373016
selection_background  #d2c6a1
url_color             #dcc66e

color0   #16130b
color1   #fd7f71
color2   #7ddc6e
color3   #ffe872
color4   #d1b753
color5   #655308
color6   #dcc66e
color7   #e7e4d9
color8   #8f8c84
color9   #ffa89f
color10  #b2ffa5
color11  #fff0a5
color12  #f2dd8b
color13  #ffeda5
color14  #fff3c5
color15  #fffdf8
