name: Daily Release

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine new tag
        id: tagger
        run: |
          today=$(date +'%Y.%m.%d')
          echo "Today: $today"

          # List tags for today
          tags_today=$(git tag --list "${today}.*" | sort -V)
          echo "Tags today:"
          echo "$tags_today"

          if [ -z "$tags_today" ]; then
            new_tag="${today}.0"
          else
            last_tag=$(echo "$tags_today" | tail -n 1)
            last_num=$(echo "$last_tag" | awk -F. '{print $NF}')
            new_num=$((last_num + 1))
            new_tag="${today}.${new_num}"
          fi

          echo "New tag: $new_tag"
          echo "tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.tagger.outputs.tag }}
          git push origin ${{ steps.tagger.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          generate_release_notes: true
