name: Create Tag and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: get_date
        run: |
          date=$(date +"%Y.%m.%d")
          echo "DATE=$date" >> $GITHUB_OUTPUT

      - name: Get next tag number
        id: get_next_tag
        run: |
          $DATE=${{ steps.get_date.outputs.DATE }}
          tags=$(git tag -l --sort=-creatordate)
          next_tag_number=0
          for tag in $tags; do
            if [[ $tag =~ ^$DATE\.([0-9]+)$ ]]; then
              next_tag_number=$((next_tag_number > ${BASH_REMATCH[1]} ? next_tag_number : ${BASH_REMATCH[1]} + 1))
            fi
          done
          echo "NEXT_TAG_NUMBER=$next_tag_number" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          $DATE="${{ steps.get_date.outputs.DATE }}"
          $NEXT_TAG_NUMBER=${{ steps.get_next_tag.outputs.NEXT_TAG_NUMBER }}

          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "${DATE}.${NEXT_TAG_NUMBER}" -m "Automated tag"
          git push origin "${DATE}.${NEXT_TAG_NUMBER}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.get_date.outputs.DATE }}.${{ steps.get_next_tag.outputs.NEXT_TAG_NUMBER }}"
          name: "Release ${{ steps.get_date.outputs.DATE }}.${{ steps.get_next_tag.outputs.NEXT_TAG_NUMBER }}"
          draft: false
          prerelease: false
          generate_release_notes: true