name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        run: |
          date=$(date +"%Y.%m.%d")
          echo "DATE=$date" >> $GITHUB_ENV

      - name: Get next tag number
        run: |
          tags=$(git tag -l --sort=-creatordate)
          next_tag_number=0
          for tag in $tags; do
            if [[ $tag =~ ^$DATE\.([0-9]+)$ ]]; then
              next_tag_number=$((next_tag_number > ${BASH_REMATCH[1]} ? next_tag_number : ${BASH_REMATCH[1]} + 1))
            fi
          done
          echo "NEXT_TAG_NUMBER=$next_tag_number" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a "${DATE}.${NEXT_TAG_NUMBER}" -m "Automated tag"
          git push origin "${DATE}.${NEXT_TAG_NUMBER}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${DATE}.${NEXT_TAG_NUMBER}"
          name: "Release ${DATE}.${NEXT_TAG_NUMBER}"
          draft: false
          prerelease: false
          generate_release_notes: true